### ISSUE TITLE
ValueError: 'bboxes' cannot be empty

### ISSUE THREAD

**Issue by mosoriob** [mintproject/droughtIndices#1]
How to reproduce?

```
$ docker run -ti mintproject/droughtindices bash
$ mkdir results
$ wget https://data.mint.isi.edu/files/raw-data/GLDAS2.1_TP_2000_2018.nc
$ python /usr/bin/WM_climate_indices.py GLDAS GLDAS2.1_TP_2000_2018.nc results SPI [23,48,3,15] gamma monthly 6 2000 2017 2008 2017  True
Traceback (most recent call last):
  File "/usr/bin/WM_climate_indices.py", line 813, in <module>
    visualizeDroughtIndex(ds, dir_out, info, dataset_type)
  File "/usr/bin/WM_climate_indices.py", line 656, in visualizeDroughtIndex
    vmax =4)
  File "/opt/conda/lib/python3.7/site-packages/matplotlib/pyplot.py", line 2524, in contourf
    **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/cartopy/mpl/geoaxes.py", line 1404, in contourf
    for col in result.collections
  File "/opt/conda/lib/python3.7/site-packages/matplotlib/transforms.py", line 701, in union
    raise ValueError("'bboxes' cannot be empty")
ValueError: 'bboxes' cannot be empty
(base) root@3a77ab959600:/#
```

## Results

http://inf.utfsm.cl/~mosorio/results/SPI_MINT_GLDAS_2000-01-01_2017-12-01_9b7fee03-b949-46dc-843c-1c2223c4e392.nc
http://inf.utfsm.cl/~mosorio/results/SPI_MINT_GLDAS_2000-01-01_2017-12-01_3156a63d-221a-4fb1-8c17-577a6c78d593.nc

## Packages

```
name: base
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - asn1crypto=1.0.1=py37_0
  - blas=1.0=mkl
  - bokeh=1.4.0=py37_0
  - bottleneck=1.2.1=py37h035aef0_1
  - bzip2=1.0.8=h7b6447c_0
  - ca-certificates=2019.11.28=hecc5488_0
  - cartopy=0.17.0=py37h423102d_1009
  - certifi=2019.11.28=py37_0
  - cffi=1.12.3=py37h2e261b9_0
  - cftime=1.0.4.2=py37hdd07704_0
  - chardet=3.0.4=py37_1003
  - click=7.0=py37_0
  - cloudpickle=1.2.2=py_0
  - conda=4.8.1=py37_0
  - conda-package-handling=1.6.0=py37h7b6447c_0
  - cryptography=2.7=py37h1ba5d50_0
  - curl=7.67.0=hbc83047_0
  - cycler=0.10.0=py37_0
  - cytoolz=0.10.1=py37h7b6447c_0
  - dask=2.2.0=py_0
  - dask-core=2.2.0=py_0
  - dbus=1.13.12=h746ee38_0
  - distributed=2.5.2=py_0
  - expat=2.2.6=he6710b0_0
  - fontconfig=2.13.0=h9420a91_0
  - freetype=2.9.1=h8a8886c_1
  - fsspec=0.6.2=py_0
  - geos=3.8.0=he1b5a44_0
  - glib=2.63.1=h5a9c865_0
  - gst-plugins-base=1.14.0=hbbd80ab_1
  - gstreamer=1.14.0=hb453b48_1
  - hdf4=4.2.13=h3ca952b_2
  - hdf5=1.10.4=hb1b8bf9_0
  - heapdict=1.0.1=py_0
  - icu=58.2=h9c2bf20_1
  - idna=2.8=py37_0
  - intel-openmp=2019.4=243
  - jinja2=2.10.3=py_0
  - jpeg=9b=h024ee3a_2
  - kiwisolver=1.1.0=py37he6710b0_0
  - krb5=1.16.4=h173b8e3_0
  - libblas=3.8.0=14_mkl
  - libcblas=3.8.0=14_mkl
  - libcurl=7.67.0=h20c2e04_0
  - libedit=3.1.20181209=hc058e9b_0
  - libffi=3.2.1=hd88cf55_4
  - libgcc-ng=9.1.0=hdf63c60_0
  - libgfortran-ng=7.3.0=hdf63c60_0
  - liblapack=3.8.0=14_mkl
  - libnetcdf=4.6.1=h11d0813_2
  - libpng=1.6.37=hbc83047_0
  - libssh2=1.8.2=h1ba5d50_0
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - libtiff=4.1.0=h2733197_0
  - libuuid=1.0.3=h1bed415_2
  - libxcb=1.13=h1bed415_1
  - libxml2=2.9.9=hea5a465_1
  - locket=0.2.0=py37_1
  - markupsafe=1.1.1=py37h7b6447c_0
  - matplotlib=3.1.0=py37h5429711_0
  - matplotlib-base=2.2.4=py37hfd891ef_0
  - mkl=2019.4=243
  - mkl-service=2.3.0=py37he904b0f_0
  - mkl_fft=1.0.15=py37ha843d7b_0
  - mkl_random=1.1.0=py37hd6b4f25_0
  - msgpack-python=0.6.1=py37hfd86e86_1
  - ncurses=6.1=he6710b0_1
  - netcdf4=1.4.2=py37h808af73_0
  - numpy=1.17.4=py37hc1035e2_0
  - numpy-base=1.17.4=py37hde5b4d6_0
  - olefile=0.46=py37_0
  - openssl=1.1.1d=h516909a_0
  - owslib=0.19.0=py_2
  - packaging=20.0=py_0
  - pandas=0.25.3=py37he6710b0_0
  - partd=1.1.0=py_0
  - pcre=8.43=he6710b0_0
  - pillow=7.0.0=py37hb39fc2d_0
  - pip=19.2.3=py37_0
  - proj=6.2.1=hc80f0dc_0
  - psutil=5.6.7=py37h7b6447c_0
  - pycosat=0.6.3=py37h14c3975_0
  - pycparser=2.19=py37_0
  - pyepsg=0.4.0=py_0
  - pykdtree=1.3.1=py37hc1659b7_1002
  - pyopenssl=19.0.0=py37_0
  - pyparsing=2.4.6=py_0
  - pyproj=2.4.2.post1=py37h12732c1_0
  - pyqt=5.9.2=py37h05f1152_2
  - pyshp=2.1.0=py_0
  - pysocks=1.7.1=py37_0
  - python=3.7.4=h265db76_1
  - python-dateutil=2.8.1=py_0
  - pytz=2019.3=py_0
  - pyyaml=5.2=py37h7b6447c_0
  - qt=5.9.7=h5867ecd_1
  - readline=7.0=h7b6447c_5
  - requests=2.22.0=py37_0
  - ruamel_yaml=0.15.46=py37h14c3975_0
  - scipy=1.4.1=py37h921218d_0
  - setuptools=41.4.0=py37_0
  - shapely=1.6.4=py37h5d51c17_1007
  - sip=4.19.8=py37hf484d3e_0
  - six=1.12.0=py37_0
  - sortedcontainers=2.1.0=py37_0
  - sqlite=3.30.1=h7b6447c_0
  - tblib=1.6.0=py_0
  - tk=8.6.10=hed695b0_0
  - toolz=0.10.0=py_0
  - tornado=6.0.3=py37h7b6447c_0
  - tqdm=4.36.1=py_0
  - urllib3=1.24.2=py37_0
  - wheel=0.33.6=py37_0
  - xarray=0.14.1=py_1
  - xz=5.2.4=h14c3975_4
  - yaml=0.1.7=had09818_2
  - zict=1.0.0=py_0
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.3.7=h0b5b093_0
  - pip:
    - attrs==19.3.0
    - climate-indices==1.0.8
    - imageio==2.6.1
    - imageio-ffmpeg==0.3.0
    - importlib-metadata==1.4.0
    - llvmlite==0.31.0
    - more-itertools==8.1.0
    - nco==1.0.0
    - numba==0.47.0
    - pluggy==0.13.1
    - py==1.8.1
    - pytest==5.3.4
    - wcwidth==0.1.8
    - zipp==2.0.1
prefix: /opt/conda
```

**Comment by khider** [comment]
Fixed in 1.1
